theme: minima
title: Shijie (Christopher) Wang
author: Shijie (Christopher) Wang
email: Christophertlal@outlook.com
description: > Shijie Wang, who was graduated from Xiâ€™an Jiaotong-Liverpool University, is interested in Psycholinguistics, Bi/Multilingualism, Individual Difference, and Quantitative Research Method. # this means to ignore newlines until "baseurl:"

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
